name: FooBar Http-Echo CI

on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main

jobs:
    CI:
        runs-on: ubuntu-latest
        env:
            ACTIONS_STEP_DEBUG: true
            ACTIONS_RUNNER_DEBUG: true
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
       
            - name: Setup Docker
              uses: docker/setup-qemu-action@v2

            - name: Create KinD Cluster
              run:  kind create cluster --config kindCluster/config.yml

            - name: Deploy Ingress Controller
              run: bash .github/scripts/install_ingress.sh

            - name: Deploy FooBar
              run : bash .github/scripts/deploy_foobar.sh

            - name: Setup metalLB
              run: bash .github/scripts/setup_metalLB.sh

            - name: Grace Period
              run : sleep 40

            - name: Update hosts file with hostnames
              run: bash .github/scripts/update_hostsfile.sh

            - name: Test Deployment
              run : |
                curl foo.localhost
                curl bar.localhost




