name: FooBar Http-Echo CI

on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main

jobs:
    CI:
        runs-on: ubuntu-latest
        env:
            ACTIONS_STEP_DEBUG: true
            ACTIONS_RUNNER_DEBUG: true
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
       
            - name: Setup Docker
              uses: docker/setup-qemu-action@v2

            - name: Install KinD
              run: |
                curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.18.0/kind-linux-amd64
                chmod +x ./kind
                sudo mv ./kind /usr/local/bin/kind

            - name: Create KinD Cluster
              run:  kind create cluster --config kindCluster/config.yml

